GET http://localhost:5234/tasks
###
GET http://localhost:5234/tasks/1
###
GET http://localhost:5234/tasks/2
###
GET http://localhost:5234/tasks/4
###
POST http://localhost:5234/tasks/new
Content-Type: application/json

{
  "title": "Cook dinner",
  "description": "I was thinking pizza",
  "complete": false,
  "createdAt": "2025-11-17T15:04:57.074668-05:00",
  "completedAt": "2025-11-17T15:04:57.0746681-05:00"
}