GET http://localhost:5234/tasks
###
GET http://localhost:5234/tasks/1
###
GET http://localhost:5234/tasks/6
###
GET http://localhost:5234/tasks/40
###
POST http://localhost:5234/tasks/new
Content-Type: application/json

{
  "title": "eee dinner",
  "description": "I was thinking pizza",
  "PriorityId": "1",
  "createdAt": "2025-11-18T18:05:19.2162004"
}
###
PUT http://localhost:5234/tasks/1/edit
Content-Type: application/json

{
  "title": "Wash Dishes",
  "description": "222g pizza",
  "PriorityId": 1,
  "complete": true,
  "createdAt": "2025-11-18T18:05:19.2162004",
  "completedAt": "2025-11-17T15:18:03.4550661-05:00"
}
###
DELETE http://localhost:5234/tasks/4